# Generated by Django 4.0.3 on 2022-05-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_and_reservation', '0004_alter_itemvariation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_note',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Poznámka k rezervaci'),
        ),
    ]
