# Generated by Django 4.0.3 on 2022-05-14 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_and_reservation', '0005_alter_reservation_reservation_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveditem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Počet kusů'),
        ),
    ]
