# Generated by Django 4.0.3 on 2022-05-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_and_reservation', '0006_alter_reserveditem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveditem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Počet kusů'),
        ),
    ]
