# Generated by Django 4.0.3 on 2022-05-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_and_reservation', '0007_alter_reserveditem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_number',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Rezervační číslo'),
        ),
        migrations.AlterField(
            model_name='reserveditem',
            name='quantity',
            field=models.IntegerField(verbose_name='Počet kusů'),
        ),
    ]
